version: '3.9'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017" # 테스트 전용 포트
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data-test:/data/db

  auth-svc:
    build: ./auth-svc
    container_name: auth-svc-test
    restart: unless-stopped
    env_file:
      - .env.test
    ports:
      - "${AUTH_PORT:-3100}:3100"
    depends_on:
      - mongo

  event-svc:
    build: ./event-svc
    container_name: event-svc-test
    restart: unless-stopped
    env_file:
      - .env.test
    ports:
      - "${EVENT_PORT:-3200}:3200"
    depends_on:
      - mongo

  gateway-svc:
    build: ./gateway-svc
    container_name: gateway-svc-test
    restart: unless-stopped
    env_file:
      - .env.test
    ports:
      - "${GATEWAY_PORT:-3300}:3300"
    depends_on:
      - auth-svc
      - event-svc

volumes:
  mongo-data-test: